modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="drone_detector"
version="1.0.0"
displayName="Drone Detector"
authors="Liko"
description='''
Detector for UAVs. Beeps when a drone is in range.
'''

[[dependencies.drone_detector]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.drone_detector]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"