modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"

[[mods]]
modId="drone_detector"             # ← ваш modid
version="${file.jarVersion}"
displayName="DetectorUAV"
authors="NikitaLiko"
description='''Client/server drone detector companion'''

# Зависимости прописываются ТОЛЬКО под id вашего мода:
[[dependencies.drone_detector]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.drone_detector]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
